// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("sit")>]
[<assembly: AssemblyProductAttribute("sit")>]
[<assembly: AssemblyDescriptionAttribute("Starter kit for UI automation with canopy")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "sit"
    let [<Literal>] AssemblyProduct = "sit"
    let [<Literal>] AssemblyDescription = "Starter kit for UI automation with canopy"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
